#!/usr/bin/env python3
"""CP 10.6 — tracking error and gimbal saturation against disturbance level.

Design §1.3's central claim is that the disturbance can exceed the actuator's
authority outright. The checkpoint asks for the chart that says WHERE, and for
the sentence "the loop breaks down above X" to be backed by it.

The axis is spec row 25's platform motion, scaled up and pointed AGAINST the
target's own motion so the two demands add. CP 10.3 shows why it is the
difference of the rates that matters: the commanded boresight has to move at
(target rate - drift rate), because the measurement is reconstructed through
the commanded boresight and the drift is therefore absorbed into the filter's
velocity state. Opposing drift is the case where absorbing it costs rate.

The predicted breakdown, from the geometry alone:

    mount ceiling      5 deg/s = 87266 urad/s = 800 px/s per axis
    demand             200 + d px/s along the target's diagonal
    ceiling reached    d = 600 px/s

The variants are generated here rather than committed as scenario files: the
quantity varied lives inside [[disturbance.platform]], an array of tables,
while --set addresses dotted keys. Nine near-identical scenario files to vary
one number is the duplication scenarios/control/fast_linear.toml's own header
warns about.
"""

import argparse
import json
import math
import os
import subprocess
import sys

DRIFTS = [0, 100, 200, 300, 400, 500, 600, 700, 800]
TARGET_SPEED_PX_S = 200.0


def run_one(binary, base_toml, drift_px_s, out_dir, duration):
    """One headless run with the platform drift scaled to `drift_px_s`."""
    variant = os.path.join(out_dir, f"d{drift_px_s}.toml")
    comp = drift_px_s / math.sqrt(2.0)
    with open(variant, "w", encoding="utf-8") as fh:
        fh.write(base_toml)
        fh.write("\n# generated by tools/cp106_sweep.py — do not edit\n")
        fh.write("[[disturbance.platform]]\nkind = \"linear\"\n")
        # Negative: opposing the target, so the rate demands add.
        fh.write(f"velocity_px_s = [{-comp:.4f}, {-comp:.4f}]\n")

    run_dir = os.path.join(out_dir, f"r{drift_px_s}")
    subprocess.run(
        [binary, "--headless", "--scenario", variant, "--duration", str(duration),
         "--no-csv", "--no-report", "--quiet", "--out", run_dir],
        check=True, stdout=subprocess.DEVNULL)
    with open(os.path.join(run_dir, "run.json"), encoding="utf-8") as fh:
        m = json.load(fh)["metrics"]
    return m["tracking"]["rms_px"], 100.0 * m["plant"]["saturation_frac"]


def main(argv):
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--binary", required=True)
    ap.add_argument("--scenario", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--duration", default="8")
    a = ap.parse_args(argv)

    sweep_dir = os.path.join(a.out, "cp106")
    os.makedirs(sweep_dir, exist_ok=True)
    with open(a.scenario, encoding="utf-8") as fh:
        base = fh.read()

    err, sat = [], []
    print("  drift      demand     tracking RMS    saturation")
    for d in DRIFTS:
        e, s = run_one(a.binary, base, d, sweep_dir, a.duration)
        err.append((d, e))
        sat.append((d, s))
        print(f"  {d:4d} px/s  {TARGET_SPEED_PX_S + d:6.0f} px/s  "
              f"{e:10.2f} px  {s:10.2f} %")

    # The stateable sentence the checkpoint asks for. "Breaks down" is defined
    # against spec row 17's own budget rather than against a shape on a chart:
    # the first disturbance level at which the loop can no longer hold the
    # requirement it is graded on.
    broke = next((d for d, e in err if e > 10.0), None)
    if broke is None:
        print("\n  the loop held row 17's 10 px budget at every level tested")
    else:
        below = [d for d, e in err if e <= 10.0]
        print(f"\n  row 17's 10 px budget is held up to {max(below) if below else 0} px/s "
              f"of platform drift and lost at {broke} px/s")
        print(f"  (predicted rate-ceiling crossing: 600 px/s, where the demand "
              f"reaches the mount's 800 px/s)")

    def xy(pairs):
        return ",".join(f"{x}:{y:.4f}" for x, y in pairs)

    plot = os.path.join(os.path.dirname(os.path.abspath(__file__)), "plot_control.py")
    for name, data, ylabel, title, sub in (
        ("cp106.svg", err, "tracking error, px RMS",
         "CP 10.6 — where the loop breaks down",
         "200 px/s target, spec row 25 platform motion scaled up and opposing it"),
        ("cp106_saturation.svg", sat, "saturation, % of ticks",
         "CP 10.6 — gimbal saturation against disturbance",
         "fraction of truth ticks spent at the rate ceiling"),
    ):
        subprocess.run(
            [sys.executable, plot, "-o", os.path.join(a.out, name), "--xy",
             "--title", title, "--subtitle", sub,
             "--xlabel", "platform drift, px/s", "--ylabel", ylabel,
             "--vline", "600", "--vlabel", "mount rate ceiling: demand = 800 px/s",
             f"{ylabel.split(',')[0]}={xy(data)}"],
            check=True)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
