#!/usr/bin/env python3
"""CP 13.2 — all five search strategies benchmarked, and the camp-and-wait crossover.

§10.5 asks for "mean acquisition time per strategy; camp-and-wait crossover
plotted against target speed", and calls the crossover "a small, genuine,
defensible result".

THE ARGUMENT, BEFORE THE NUMBERS
--------------------------------
A cold search is a race between two clocks.

  the sweep     25 tiles at ~0.75 s each is about 18.7 s at 5 deg/s (CP 6.7
                measures the bound)
  the lap       a target on a closed path returns to any given point once per
                lap

If the lap is shorter than the sweep, WAITING WINS — and waiting is free, while
searching spends the mount's entire rate budget and motion-blurs every frame it
exposes while slewing. The naive answer ("always search") is wrong, which is
what makes the crossover worth measuring rather than asserting.

The axis is target speed on a fixed circular path, so faster means a shorter
lap. The beacon starts at a random position (spec row 11), which is the
condition the cold-acquisition metric is defined for.
"""

import argparse
import json
import os
import subprocess
import sys

STRATEGIES = ["spiral", "raster", "probabilistic", "camp_and_wait"]
SPEEDS = [40, 80, 160, 320, 640]
SEEDS = list(range(1, 9))


RADIUS_PX = 600.0


def variant(base_toml, out_dir, speed):
    """The base scenario with a circular path at `speed`.

    Generated rather than committed, and for the reason cp106_sweep.py gives:
    the quantity varied lives inside [[target.motion]], an array of tables,
    while --set addresses dotted keys. Five near-identical scenario files to
    vary one number is the duplication scenarios/control/fast_linear.toml's own
    header warns about.
    """
    path = os.path.join(out_dir, f"v{speed}.toml")
    if not os.path.exists(path):
        period = 2.0 * 3.14159265358979 * RADIUS_PX / speed
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(base_toml)
            fh.write("\n# generated by tools/cp132_sweep.py - do not edit\n")
            fh.write("[[target.motion]]\nkind = \"circular\"\n")
            fh.write(f"radius_px = {RADIUS_PX}\nperiod_s = {period:.6f}\n")
    return path


def run(binary, scenario, out_dir, strategy, speed, seed):
    tag = f"{strategy}_{speed}_{seed}"
    run_dir = os.path.join(out_dir, tag)
    subprocess.run(
        [binary, "--headless", "--scenario", scenario, "--duration", "45",
         "--seed", str(seed),
         "--set", f"search.strategy=\"{strategy}\"",
         "--no-csv", "--no-report", "--quiet", "--out", run_dir],
        check=True, stdout=subprocess.DEVNULL)
    with open(os.path.join(run_dir, "run.json"), encoding="utf-8") as fh:
        a = json.load(fh)["metrics"]["acquisition"]
    # A run that never acquires is not a missing sample — it is the worst
    # possible sample, and dropping it would flatter whichever strategy failed
    # most often. Censored at the run length, which is what a survival analysis
    # would do and is the honest floor on "how long did it take".
    return a["cold_s"] if a["acquired"] else 45.0, bool(a["acquired"])


def main(argv):
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--binary", required=True)
    ap.add_argument("--scenario", required=True)
    ap.add_argument("--out", required=True)
    a = ap.parse_args(argv)

    out_dir = os.path.join(a.out, "cp132")
    os.makedirs(out_dir, exist_ok=True)
    with open(a.scenario, encoding="utf-8") as fh:
        base = fh.read()

    print(f"  {len(SEEDS)} seeds per cell, 45 s cap, beacon at a random start\n")
    header = "  speed  lap_s  " + "".join(f"{s:>16s}" for s in STRATEGIES)
    print(header)

    table = {s: [] for s in STRATEGIES}
    for speed in SPEEDS:
        # Circular path, radius 600 px: lap = 2*pi*r / v.
        lap = 2.0 * 3.14159265 * RADIUS_PX / speed
        sc  = variant(base, out_dir, speed)
        row = f"  {speed:5d}  {lap:5.1f}  "
        for strat in STRATEGIES:
            times, hits = [], 0
            for seed in SEEDS:
                t, ok = run(a.binary, sc, out_dir, strat, speed, seed)
                times.append(t)
                hits += 1 if ok else 0
            mean = sum(times) / len(times)
            table[strat].append((speed, mean, hits))
            row += f"{mean:9.2f}s {hits}/{len(SEEDS)}".rjust(16)
        print(row)

    print("\n  Camp-and-wait against the best searching strategy:")
    crossover = None
    for i, speed in enumerate(SPEEDS):
        wait = table["camp_and_wait"][i][1]
        best_search = min(table[s][i][1] for s in STRATEGIES if s != "camp_and_wait")
        verdict = "camp-and-wait" if wait < best_search else "search"
        if wait < best_search and crossover is None:
            crossover = speed
        print(f"    {speed:4d} px/s   wait {wait:6.2f}s vs search {best_search:6.2f}s"
              f"   -> {verdict}")

    if crossover is None:
        print("\n  No crossover in this range: searching wins at every speed tested.")
    else:
        print(f"\n  CROSSOVER at {crossover} px/s: past this, staying still beats "
              f"searching.")

    def xy(pairs):
        return ",".join(f"{s}:{m:.4f}" for s, m, _ in pairs)

    plot = os.path.join(os.path.dirname(os.path.abspath(__file__)), "plot_control.py")
    args = [sys.executable, plot, "-o", os.path.join(a.out, "cp132.svg"), "--xy",
            "--title", "CP 13.2 - mean cold acquisition time by search strategy",
            "--subtitle", "circular path, radius 600 px; faster target = shorter lap",
            "--xlabel", "target speed, px/s", "--ylabel", "mean acquisition, s"]
    if crossover is not None:
        args += ["--vline", str(crossover), "--vlabel", "camp-and-wait crossover"]
    for strat in STRATEGIES:
        args.append(f"{strat}={xy(table[strat])}")
    subprocess.run(args, check=True)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
